name: Cloudwatch create log group if not exists

inputs:
  log_group_name:
    description: Log group name
    required: true
    type: string

  log_group_retention_in_days:
    description: Log group retention in days
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Create log group if not exists
      shell: bash
      run: |
        aws logs create-log-group |
          --log-group-name ${{ inputs.log_group_name }} || true;

    - name: Put log group retention policy
      shell: bash
      run: |
        aws logs put-retention-policy |
          --log-group-name ${{ inputs.log_group_name }}
          --retention-in-days ${{ inputs.log_group_retention_in_days }}
