name: TAGS get resource ARN

inputs:
  tag_key:
    description: AWS tag key
    required: false
    type: string
    default: Name

  tag_values:
    description: AWS tag value
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Get resouce by tag
      shell: bash
      run: |
        ARN=$(\
          aws resourcegroupstaggingapi get-resources \
            --tag-filters "Key=${{ inputs.tag_key }},Values=${{ inputs.tag_values }}" | \
          jq -r '.ResourceTagMappingList | .[] | .ResourceARN' \
        );
        echo "arn=$ARN" >> $GITHUB_OUTPUT;