name: ECR create repository if not exists

inputs:
  repository_name:
    description: Repository name
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Create repository if not exists
      shell: bash
      run: |
        aws ecr describe-repositories \
          --repository-names ${{ inputs.repository_name }} || \
        aws ecr create-repository \
          --repository-name ${{ inputs.repository_name }} \
          --image-scanning-configuration scanOnPush=true \
          --image-tag-mutability MUTABLE
