name: Docker build and push

inputs:
  repository_name:
    description: Repository name
    required: true
    type: string

  image_tag:
    description: Image tag
    required: false
    type: string
    default: dev

  cicd_git_token:
    required: false
    description: Git access token

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.repository_name }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        GIT_TOKEN: ${{ inputs.cicd_git_token }}
      run: |
        if [[ $GIT_TOKEN ]]
        then
          BUILD_ARG="--build-arg GIT_TOKEN=$GIT_TOKEN"
        fi;
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $BUILD_ARG;
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG;
        echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
