name: ECS prepare service

inputs:
  service_name:
    description: Service name
    required: true
    type: string

  region:
    description: AWS region
    required: true
    type: string

  listener_port:
    description: Service ELB listener port
    required: true
    type: string

  target_group_port:
    description: Service ELB target group port
    required: true
    type: string

  service_suffix:
    description: Service resources naming suffix
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ORG_ID }}:role/github-actions-cicd-role
        role-session-name: cicd
        aws-region: ${{ inputs.region }}
      shell: bash

    - name: Echo
      run: |
        echo "ALL GOOD :))"
      shell: bash