name: AWS ECR create repository

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string

      repo_name:
        description: Repository name
        required: true
        type: string

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::778942390430:role/github-actions-cicd-role
          role-session-name: cicd
          aws-region: ap-northeast-2

      - name: Configure suffix
        if: ${{ inputs.environment == 'development' }}
        run: echo "suffix=-dev" >> $GITHUB_OUTPUT

      - name: Create ECR repository
        run: |
          aws ecr describe-repositories \
            --repository-names ${{ inputs.repo_name }}{{ steps.vars.outputs.suffix }} \
            --region ap-northeast-2 || \
          aws ecr create-repository \
            --repository-name ${{ inputs.repo_name }}{{ steps.vars.outputs.suffix }} \
            --region ap-northeast-2