name: AWS ECR create repository

env:
  SUFFIX: ""

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string

      repo_name:
        description: Repository name
        required: true
        type: string

jobs:
  create:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::778942390430:role/github-actions-cicd-role
          role-session-name: cicd
          aws-region: ap-northeast-2
        permissions:
          packages: write
          contents: read
          id-token: write

      - name: Configure suffix
        if: ${{ inputs.environment == 'development' }}
        env:
          SUFFIX: -dev
        run: echo $SUFFIX

      - name: Create ECR repository
        run: |
          aws ecr describe-repositories \
            --repository-names ${{ inputs.repo_name }}$SUFFIX \
            --region ap-northeast-2 || \
          aws ecr create-repository \
            --repository-name ${{ inputs.repo_name }}$SUFFIX \
            --region ap-northeast-2