name: AWS ECS create service task definition

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string

      region:
        description: AWS region
        required: false
        type: string
        default: ap-northeast-2

      elb_target_group_port:
        description: Service ELB target group port
        required: false
        type: string
        default: 8000

      task_def_name:
        description: Service name
        required: true
        type: string
      
      repo_name:
        description: Repository name
        required: true
        type: string

jobs:

  setup:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::778942390430:role/github-actions-cicd-role
          role-session-name: cicd
          aws-region: ${{ inputs.region }}

      - name: Configure dev
        if: ${{ inputs.environment == 'development' }}
        run: |
          echo "SUFFIX=-dev" >> $GITHUB_ENV;
          echo "CPU=0.25 vCPU" >> $GITHUB_ENV;
          echo "MEMORY=0.5 GB" >> $GITHUB_ENV;
          echo "RETENTION=3" >> $GITHUB_ENV;

      - name: Create task definition
        run: |
          aws ecs register-task-definition \
            --region ${{ inputs.region }} \
            --family ${{ inputs.task_def_name }}${{ env.SUFFIX }} \
            --task-role-arn "arn:aws:iam::778942390430:role/ecs-tasks-role" \
            --execution-role-arn "arn:aws:iam::778942390430:role/ecs-tasks-execution-role" \
            --network-mode "awsvpc" \
            --cpu "${{ env.CPU }}" \
            --memory "${{ env.MEMORY }}" \
            --container-definitions "[{\"name\":\"main\",\"image\":\"778942390430.dkr.ecr.ap-northeast-2.amazonaws.com\/${{ inputs.repo_name }}\",\"portMappings\":[{\"containerPort\":${{ inputs.elb_target_group_port }}}],\"logConfiguration\": {\"logDriver\":\"awslogs\",\"options\":{\"awslogs-group\":\"\/ecs\/${{ inputs.task_def_name }}${{ env.SUFFIX }}\",\"awslogs-region\": \"${{ inputs.region }}\",\"awslogs-stream-prefix\":\"ecs\"}}}]" \
            --runtime-platform cpuArchitecture=ARM64,operatingSystemFamily=LINUX;

      - name: Create task log group
        run: |
          aws logs create-log-group --log-group-name "/ecs/${{ inputs.repo_name }}${{ env.SUFFIX }}" || true;
          aws logs put-retention-policy --log-group-name "/ecs/${{ inputs.repo_name }}${{ env.SUFFIX }}" --retention-in-days ${{ env.RETENTION }}