name: Setup ECR repository

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string
        default: development

      region:
        description: AWS region
        required: false
        type: string
        default: ap-northeast-2

      repo_name:
        description: Repository name
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::778942390430:role/github-actions-cicd-role
          role-session-name: cicd
          aws-region: ${{ inputs.region }}

      - name: Configure dev
        if: ${{ inputs.environment == 'development' }}
        run: echo "SUFFIX=-dev" >> $GITHUB_ENV

      - name: Create ECR repository
        run: |
          aws ecr describe-repositories \
            --repository-names ${{ inputs.repo_name }}${{ env.SUFFIX }} \
            --region ${{ inputs.region }} || \
          aws ecr create-repository \
            --repository-name ${{ inputs.repo_name }}${{ env.SUFFIX }} \
            --region ${{ inputs.region }}