name: AWS ECS create service

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string

      region:
        description: AWS region
        required: true
        type: string
        default: ap-northeast-2
      
      repo_name: 
        description: Repository name
        required: true
        type: string

      service_name:
        description: Service name
        required: true
        type: string

      service_count:
        description: Service count
        required: true
        type: string

      task_def_name:
        description: Task definition name
        required: true
        type: string

jobs:

  setup:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::778942390430:role/github-actions-cicd-role
          role-session-name: cicd
          aws-region: ${{ inputs.region }}

      - name: Configure dev
        if: ${{ inputs.environment == 'development' }}
        run: |
          echo "SUFFIX=-dev" >> $GITHUB_ENV;
          echo "CLUSTER=funpik-development-cluster" >> $GITHUB_ENV;
          echo "SUBNETS=subnet-0afbeac3ff6e6f850,subnet-0287d8045719d8f0c" >> $GITHUB_ENV;
          echo "SG=sg-0063f5d32aba32ec7" >> $GITHUB_ENV;

      - name: Get target group
        run: echo "TG=$(\
          aws resourcegroupstaggingapi get-resources \
            --tag-filters Key=Name,Values=${{ inputs.elb_target_group_name }}${{ env.SUFFIX }}-tg \
            --region ${{ inputs.region }} | jq -r '.ResourceTagMappingList | .[] | .ResourceARN' \
        )" >> $GITHUB_ENV;

      - name: Get service
        run: echo "SVC=$(\
          aws resourcegroupstaggingapi get-resources \
            --tag-filters Key=Name,Values=${{ inputs.service_name }}${{ env.SUFFIX }}-svc \
            --region ${{ inputs.region }} | jq -r '.ResourceTagMappingList | .[] | .ResourceARN' \
        )" >> $GITHUB_ENV;

      - name: Create service
        if: ${{ env.SVC == '' }}
        run: |
          aws ecs create-service \
            --region ${{ inputs.region }} \
            --cluster ${{ env.CLUSTER }} \
            --service-name ${{ inputs.service_name }}${{ env.SUFFIX }} \
            --task-definition ${{ inputs.task_def_name }}${{ env.SUFFIX }} \
            --desired-count ${{ inputs.service_count }} \
            --capacity-provider-strategy "capacityProvider=FARGATE,weight=1,base=0" \
            --network-configuration "awsvpcConfiguration={securityGroups=[${{ env.SG }}],subnets=[${{ env.SUBNETS }}],assignPublicIp=ENABLED}" \
            --load-balancers "targetGroupArn=${{ env.TG }},containerName=main,containerPort=8000" \
            --tags key=Name,value=${{ inputs.service_name }}${{ env.SUFFIX }}-svc;