on:
  workflow_call:
    inputs:
      region:
        description: AWS region
        required: false
        type: string
        default: ap-northeast-2

      bucket_name:
        description: Bucket name
        required: true
        type: string

env:
  AWS_ORG_ID: 778942390430

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install project
        run: npm install;

      - name: Build & export
        run: |
          npm run build
          npm run export

      - uses: actions/upload-artifact@v3
        with:
          name: project-artifact
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:

      - uses: actions/download-artifact@v3
        with:
          name: project-artifact
          path: ./out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ORG_ID }}:role/github-actions-cicd-role
          role-session-name: cicd
          aws-region: ${{ inputs.region }}

      - name: Upload to S3
        run: |
          aws s3 sync ./out/. s3://{{ inputs.bucket_name }} --cache-control max-age=0